#!/sbin/busybox sh

# $1 - "default_cpu_gov"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	default_cpu_gov=$2;

	case "${default_cpu_gov}" in
		ondemand)
			echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
			echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
			echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
		;;
		ondemandplus)
			echo "ondemandplus" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			echo "ondemandplus" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
			echo "ondemandplus" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
			echo "ondemandplus" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
		;;
		interactive)
			echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			echo "interactive" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
			echo "interactive" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
			echo "interactive" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
		;;
		powersave)
			echo "powersave" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			echo "powersave" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
			echo "powersave" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
			echo "powersave" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
		;;
		intellidemand)
			echo "intellidemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			echo "intellidemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
			echo "intellidemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
			echo "intellidemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
		;;
		conservative)
			echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			echo "conservative" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
			echo "conservative" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
			echo "conservative" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
		;;
		performance)
			echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			echo "performance" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor;
			echo "performance" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor;
			echo "performance" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor;
		;;
		*)
			default_cpu_gov=ondemand;
		;;
	esac;
fi;

echo ${default_cpu_gov};
