#!/sbin/busybox sh

# $1 - "oc_controller"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

	if [ "a$2" != "a" ]; then
		oc_controller=$2;

		case "${oc_controller}" in
			ultra)
				echo "2803200" > /sys/power/cpufreq_max_limit;
				echo "2803200" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
				$BB sh /res/uci.sh cpu_max_freq 2803200;
			;;
			high)
				echo "2572800" > /sys/power/cpufreq_max_limit;
				echo "2572800" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
				$BB sh /res/uci.sh cpu_max_freq 2572800;
			;;
			stock)
				echo "2265600" > /sys/power/cpufreq_max_limit;
				echo "2265600" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
				$BB sh /res/uci.sh cpu_max_freq 2265600;
			;;
			battery)
				echo "1958400" > /sys/power/cpufreq_max_limit;
				echo "1958400" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
				$BB sh /res/uci.sh cpu_max_freq 1958400;
			;;
			*)
				oc_controller=stock;
			;;
		esac;
	fi;

echo ${oc_controller};
