#!/sbin/busybox sh

# $1 - "oc_controller"
# $2 - value=
# Created By Dorimanx

BB=/sbin/busybox

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

	if [ "a$2" != "a" ]; then
		oc_controller=$2;

		case "${oc_controller}" in
			ultra)
				echo "2803200" > /sys/power/cpufreq_max_limit;
			;;
			high)
				echo "2572800" > /sys/power/cpufreq_max_limit;
			;;
			stock)
				echo "2265600" > /sys/power/cpufreq_max_limit;
			;;
			battery)
				echo "1958400" > /sys/power/cpufreq_max_limit;
			;;
			*)
				oc_controller=stock;
			;;
		esac;
	fi;

echo ${oc_controller};
