#!/sbin/busybox sh

# $1 - "scheduler"
# $2 - value=

if [ "a$2" == "a" ]; then
        echo $scheduler;
else
        scheduler=$2;
        echo "$scheduler";
fi;

BLOCK_GOV=row;

SCHED_SET()
{
	echo "$BLOCK_GOV" > /sys/block/mmcblk0/queue/scheduler;

	if [ -e /sys/block/mmcblk1/queue/scheduler ]; then
		echo "$BLOCK_GOV" > /sys/block/mmcblk1/queue/scheduler;
	fi;
}

case "${scheduler}" in
	cfq)
		BLOCK_GOV=cfq;
		SCHED_SET;
	;;
	bfq)
		BLOCK_GOV=bfq;
		SCHED_SET;
	;;
	deadline)
		BLOCK_GOV=deadline;
		SCHED_SET;
	;;
	noop)
		BLOCK_GOV=noop;
		SCHED_SET;
	;;
	row)
		BLOCK_GOV=row;
		SCHED_SET;
	;;
	sio)
		BLOCK_GOV=sio;
		SCHED_SET;
	;;
	vr)
		BLOCK_GOV=vr;
		SCHED_SET;
	;;
	zen)
		BLOCK_GOV=zen;
		SCHED_SET;
	;;
	fifo)
		BLOCK_GOV=fifo;
		SCHED_SET;
	;;
	*)
		scheduler=row;
	;;
esac;
