#!/sbin/busybox sh

BB=/sbin/busybox

(
	if [ "$(pgrep -f "/res/customconfig/actions/push-actions/reload_settings" | wc -l)" -le "3" ]; then
		echo "Loading Config, reload STweaks after 10sec";
		# apply STweaks settings
		$BB nohup $BB sh /res/uci.sh apply > /dev/null;

		# Load Custom Modules
		if [ "$cifs_module" == "on" ]; then
			if [ -e /system/lib/modules/cifs.ko ]; then
				$BB insmod /system/lib/modules/cifs.ko;
        		fi;
		fi;

		sync;
		$BB rm -rf /data/data/com.gokhanmoral.stweaks.app/*;
		$BB pkill -f "com.gokhanmoral.stweaks.app";
		exit;
	else
		echo "Still running!!"
	fi;
)&
