#!/sbin/busybox sh

WGET_CHECK1=`ls /system/xbin/wget | wc -l` > /dev/null 2>&1;
WGET_CHECK2=`ls /system/bin/wget | wc -l` > /dev/null 2>&1;

if [ "$WGET_CHECK1" -eq "1" ] || [ "$WGET_CHECK2" -eq "1" ]; then

	mount -o remount,rw /;
	mount -o remount,rw /system;

	DNS1=`getprop net.rmnet0.dns1`;
	DNS2=`getprop net.rmnet0.dns2`;

	echo "nameserver 8.8.8.8" > /system/etc/resolv.conf;
	echo "nameserver $DNS1" >> /system/etc/resolv.conf;
	echo "nameserver $DNS2" >> /system/etc/resolv.conf;

	TMPFILE=$(mktemp -t);
	TMPFILE2=$(mktemp -t);
	OLD_VERSION=`cat /proc/version | sed 's/.*-V//g' | sed 's/-I.*//g' | sed 's/-/ /g' | awk '{print $1}'`;

	TESTCONNECTION=`wget http://www.google.com -O $TMPFILE > /dev/null 2>&1`;
	if [ $? != 0 ]; then
		echo "Problem: no internet connection! connect and try again";
	else
		wget http://www.dorimanx.com/Android-ICS/ -O $TMPFILE > /dev/null 2>&1;
		cat $TMPFILE | grep ".*-V" |  sed 's/.*-V//g' | sed 's/-I.*//g' | sed 's/[-\[].*//g' | sort -r > $TMPFILE2;

		for version in $(cat $TMPFILE2); do
			expr "$OLD_VERSION" \< "$version" >/dev/null && expr "$version" \< "8.99" >/dev/null && echo "There is a new version of this kernel available!!!" && break;
			expr "$OLD_VERSION" \< "$version" >/dev/null && expr "$OLD_VERSION" \> "9.0" >/dev/null && echo "There is a new version of this kernel available!!!" && break;
			expr "$OLD_VERSION" \= $version >/dev/null && expr "$OLD_VERSION" \< "8.99" >/dev/null && echo "You already using the most advanced kernel in the world!" && break;
			expr "$OLD_VERSION" \= $version >/dev/null && echo "You already using the most advanced kernel in the world!" && break;
		done;
	fi;

	rm $TMPFILE;
	rm $TMPFILE2;
else
	echo "Your BusyBox is not supported! Update to latest";
fi;
