#!/sbin/busybox sh

# $1 - "cpu_boost_freq"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	cpu_boost_freq=$2;

	if [ -e /sys/devices/system/cpu/cpufreq/ondemand/input_boost_freq ]; then
		echo "$cpu_boost_freq" > /sys/devices/system/cpu/cpufreq/ondemand/input_boost_freq;
		echo "$cpu_boost_freq" > /sys/module/cpu_boost/parameters/input_boost_freq;
	else
		echo "$cpu_boost_freq" > /sys/module/cpu_boost/parameters/input_boost_freq;
	fi;
fi;

echo ${cpu_boost_freq};
