#!/sbin/busybox sh

# $1 - "default_cpu_gov"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.dori/.active.profile);
. /data/.dori/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	default_cpu_gov=$2;

	case "${default_cpu_gov}" in
		ondemand)
			echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		ondemandplus)
			echo "ondemandplus" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
		;;
		HYPER)
			echo "HYPER" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		nightmare)
			echo "nightmare" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		darkness)
			echo "darkness" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		alucard)
			echo "alucard" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		pegasusq)
			echo "pegasusq" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		interactive)
			echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
		;;
		powersave)
			echo "powersave" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
		;;
		intellidemand)
			echo "intellidemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		intelliactive)
			echo "intelliactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
		;;
		conservative)
			echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
			/res/uci.sh power_mode $power_mode > /dev/null;
		;;
		performance)
			echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;
		;;
		*)
			default_cpu_gov=ondemand;
		;;
	esac;
fi;

echo ${default_cpu_gov};
