#!/sbin/busybox sh

# $1 - "ondemand_slowup"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	ondemand_slowup=$2;

	if [ -e /sys/devices/system/cpu/cpufreq/ondemand/smart_up ]; then
		echo "$ondemand_slowup" > /sys/devices/system/cpu/cpufreq/ondemand/smart_up;
	fi;
fi;

echo ${ondemand_slowup};
