#!/sbin/busybox sh

# $1 - "selinux_control"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	selinux_control=$2;

	case "${selinux_control}" in
		on)
			setenforce 1;
		;;
		off)
			setenforce 0;
		;;
		*)
			selinux_control=on;
		;;
	esac;
fi;

echo ${selinux_control};
