#!/sbin/busybox sh

# $1 - "suspend_max_freq"
# $2 - value=
# Created By Dorimanx

if [ "a$2" != "a" ]; then
	suspend_max_freq=$2;

	echo "$suspend_max_freq" > /sys/kernel/intelli_plug/suspend_max_freq;
	echo "$suspend_max_freq" > /sys/module/msm_hotplug/suspend_max_freq;
	echo "$suspend_max_freq" > /sys/kernel/alucard_hotplug/suspend_max_freq;
fi;

echo ${suspend_max_freq};
